version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: main
    reviewers:
      - jonlabelle
    commit-message:
      prefix: 'chore(deps): '
    groups:
      actions-minor:
        update-types:
          - minor
          - patch
    labels:
      - github-actions
      - dependencies
      - dependabot
