name: Setup SQL Server SSIS devops tools
description: Setup standalone SQL Server Integration Service (SSIS) devops tools
author: Jon LaBelle
branding:
  icon: database
  color: yellow

runs:
  using: composite
  steps:
    - name: Ensure Windows OS
      if: ${{ runner.os != 'Windows' }}
      shell: sh
      run: |
        echo "::error title=✘ Unsupported runner::Please choose a Windows runner to execute this action, e.g. windows-latest"
        exit 1

    - name: Output SSIS tools path
      shell: pwsh
      id: ssis-tools
      run: |
        $toolsPath = Join-Path -Path '${{ github.action_path }}' -ChildPath 'ssis-tools'
        Write-Output "ssis_tools_path=$toolsPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8NoBOM -Append

    - name: Download SSISDevOpsTools.exe
      shell: pwsh
      run: Invoke-WebRequest -Uri https://aka.ms/SSISDevOpsTools -OutFile SSISDevOpsTools.exe

    - name: Extract SSISDevOpsTools.exe
      shell: pwsh
      run: .\SSISDevOpsTools.exe /Q /C "/T:${{ steps.ssis-tools.outputs.ssis_tools_path }}"

    - name: Add SSIS tools path to system path
      shell: pwsh
      run: Write-Output "${{ steps.ssis-tools.outputs.ssis_tools_path }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8NoBOM -Append
