name: Lint YAML

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install yamllint
        run: pip install --user yamllint

      - name: Run yamllint
        run: yamllint --config-file .yamllint.yml .
