name: format check

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '**.yml'
      - '**.yaml'
      - '**.js'
      - '**.json'
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
    paths:
      - '**.md'
      - '**.yml'
      - '**.yaml'
      - '**.js'
      - '**.json'
  workflow_dispatch:

jobs:
  check-format:
    name: Format check
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Run Prettier format check
        run: npx prettier --check --log-level log '**.{md,yaml,yml,js,json}'
