name: lint yaml

on:
  push:
    branches:
      - main
    paths:
      - '**.yml'
      - '**.yaml'
      - '.github/workflows/lint-yaml.yml'
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    paths:
      - '**.yml'
      - '**.yaml'
      - '.github/workflows/lint-yaml.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install yamllint
        run: pip install --user yamllint

      - name: Run yamllint
        run: yamllint --config-file .yamllint.yml .
