name: only windows allowed

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Windows support only
    continue-on-error: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Setup SSIS tools
        uses: ./

      - name: Show SSISBuild.exe help
        run: SSISBuild.exe -h

      - name: Show SSISDeploy.exe help
        run: SSISDeploy.exe -h
