name: only windows allowed

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Windows support only
    continue-on-error: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup SSIS tools
        uses: jonlabelle/setup-ssis-devops-tools@main
      - name: Show SSISBuild.exe help
        run: SSISBuild.exe -h
        shell: pwsh
      - name: Show SSISDeploy.exe help
        run: SSISDeploy.exe -h
        shell: pwsh
